package editor.ontologies; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://lod.taxonconcept.org/ontology/txn.owl 
 * @author Auto-generated by schemagen on 04 Jun 2012 21:19 
 */
public class Txn {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://lod.taxonconcept.org/ontology/txn.owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The URI to the Accepted Name String, should only be one.</p> */
    public static final Property acceptedNameID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#acceptedNameID" );
    
    public static final Property acceptedTaxonNameID_Of = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#acceptedTaxonNameID_Of" );
    
    /** <p>The URI to an Alternative Accepted Name String</p> */
    public static final Property altAcceptedNameID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#altAcceptedNameID" );
    
    /** <p>The URI to an Alternative Accepted Name String</p> */
    public static final Property altAcceptedNameID_Of = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#altAcceptedNameID_Of" );
    
    /** <p>Links an Area to an Individual</p> */
    public static final Property areaHasIndividual = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#areaHasIndividual" );
    
    /** <p>Links an Area to a Species Concept</p> */
    public static final Property areaHasObservedSpeciesConcept = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#areaHasObservedSpeciesConcept" );
    
    /** <p>Links an Area to an Occurrence</p> */
    public static final Property areaHasOccurrence = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#areaHasOccurrence" );
    
    /** <p>Links an Area to Geonames County URI</p> */
    public static final Property areaInCounty = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#areaInCounty" );
    
    /** <p>Links an Area to Geonames State/Province URI</p> */
    public static final Property areaInStateProvince = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#areaInStateProvince" );
    
    /** <p>This is used to connect geo areas to geoname features</p> */
    public static final Property areaWithInFeature = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#areaWithInFeature" );
    
    /** <p>The author and year of the species description publication i.e (Baker, 1899)</p> */
    public static final Property authority = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#authority" );
    
    /** <p>Assumed to be equivalent to TDWG Basis of Record</p> */
    public static final Property basisOfRecord = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#basisOfRecord" );
    
    public static final Property behavioralNote = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#behavioralNote" );
    
    public static final Property binomial = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#binomial" );
    
    public static final Property botanyAuthorName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#botanyAuthorName" );
    
    public static final Property catalogCode = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#catalogCode" );
    
    public static final Property class_ = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#class" );
    
    public static final Property collectionCode = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#collectionCode" );
    
    public static final Property commonName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#commonName" );
    
    /** <p>The Links to the Status of the TaxonConcept</p> */
    public static final Property conceptStatus = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#conceptStatus" );
    
    public static final Property continent = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#continent" );
    
    public static final Property country = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#country" );
    
    public static final Property countryCode = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#countryCode" );
    
    public static final Property county = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#county" );
    
    /** <p>This is the year of the description</p> */
    public static final Property descYear = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#descYear" );
    
    public static final Property descYearOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#descYearOf" );
    
    public static final Property endDate = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#endDate" );
    
    public static final Property family = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#family" );
    
    /** <p>This is used to link a geonames feature to a geo area. For example geo:44.86528100,-87.23147800;u=10</p> */
    public static final Property featureContainsArea = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#featureContainsArea" );
    
    /** <p>The URI to the First Author</p> */
    public static final Property firstAuthorID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#firstAuthorID" );
    
    public static final Property genus = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#genus" );
    
    /** <p>The method used to determine the latitude, longitude as a URI</p> */
    public static final Property georeferenceProtocol = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#georeferenceProtocol" );
    
    /** <p>Was this location verified, controlled choices URI</p> */
    public static final Property georeferenceVerificationStatus = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#georeferenceVerificationStatus" );
    
    /** <p>associates a taxon with a habitat in which it may typically be found</p> */
    public static final Property habitat = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#habitat" );
    
    /** <p>The range is a page on the Animal Diversity Web site.</p> */
    public static final Property hasADWPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasADWPage" );
    
    public static final Property hasAcceptedName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasAcceptedName" );
    
    /** <p>The range is a page on the BBC site.</p> */
    public static final Property hasBBCPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasBBCPage" );
    
    /** <p>The Barcode of Life Integer ID</p> */
    public static final Property hasBOLD = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasBOLD" );
    
    /** <p>A page at boldsystems.org</p> */
    public static final Property hasBOLDPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasBOLDPage" );
    
    /** <p>The range is a page on the Bioimages site.</p> */
    public static final Property hasBioimagesPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasBioimagesPage" );
    
    public static final Property hasBugGuidePage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasBugGuidePage" );
    
    /** <p>The range is a uniprot pubmed uri for example http://purl.uniprot.org/pubmed/1083304</p> */
    public static final Property hasCitation = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasCitation" );
    
    /** <p>The occurrence observer or specimen collector, hasCollector?</p> */
    public static final Property hasCollector = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasCollector" );
    
    /** <p>The range is a page on the DiscoverLife.org site.</p> */
    public static final Property hasDLPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasDLPage" );
    
    /** <p>The range is a page on the http://www.discoverlife.org/ site.The range is 
     *  a page on the Discover Life Web site.</p>
     */
    public static final Property hasDiscoverLifePage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasDiscoverLifePage" );
    
    /** <p>The Encyclopedia of Life Integer ID</p> */
    public static final Property hasEOL = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasEOL" );
    
    /** <p>The range is a page on the Encyclopedia of Life site.</p> */
    public static final Property hasEOLPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasEOLPage" );
    
    public static final Property hasEUNISPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasEUNISPage" );
    
    /** <p>eBird Species Code</p> */
    public static final Property hasEbird = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasEbird" );
    
    public static final Property hasEtypePage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasEtypePage" );
    
    /** <p>This is to link between a geographical area and a taxon-like entity. The doman 
     *  and range are left blank so this can be used with different kinds of geographic 
     *  vocabularies and different kinds of taxon concept vocabularies. It should 
     *  not be used to indicate that a location has the expectation of a specific 
     *  individual specimen, but to indicate that the location has an expectation 
     *  of a specific class of organisms. For instance, it would be used to indicate 
     *  that a geographic location has an expectation of a particular species. The 
     *  use should approximate assertions similar to what one might find in a state 
     *  or country checklist.</p>
     */
    public static final Property hasExpectationOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasExpectationOf" );
    
    /** <p>The Global Biodiversity Information Facility integer ID</p> */
    public static final Property hasGBIF = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasGBIF" );
    
    public static final Property hasGBIFMap = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasGBIFMap" );
    
    /** <p>A page at GBIF.org</p> */
    public static final Property hasGBIFPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasGBIFPage" );
    
    /** <p>The ITIS ID</p> */
    public static final Property hasITIS = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasITIS" );
    
    /** <p>The range is a page on the ITIS.gov site.</p> */
    public static final Property hasITISPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasITISPage" );
    
    /** <p>Superproperty of all the links to images</p> */
    public static final Property hasImage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasImage" );
    
    public static final Property hasMapImage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasMapImage" );
    
    /** <p>The NCBI Taxonomy ID</p> */
    public static final Property hasNCBI = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasNCBI" );
    
    public static final Property hasOriginalName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasOriginalName" );
    
    public static final Property hasScientificName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasScientificName" );
    
    /** <p>This is for a string urn type identifier</p> */
    public static final Property hasSpeciesConceptID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasSpeciesConceptID" );
    
    public static final Property hasUSDAPlantsPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasUSDAPlantsPage" );
    
    /** <p>This is to link between a geographical area and a taxon-like entity. Where 
     *  the association is not known. The doman and range are left blank so this can 
     *  be used with different kinds of geographic vocabularies and different kinds 
     *  of taxon concept vocabularies. It should not be used to indicate that a location 
     *  has the expectation of a specific individual specimen, but to indicate that 
     *  the location has an expectation of a specific class of organisms. For instance, 
     *  it would be used to indicate that a geographic location has an expectation 
     *  of a particular species. The use should approximate assertions similar to 
     *  what one might find in a state or country checklist.</p>
     */
    public static final Property hasUnknownExpectationOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasUnknownExpectationOf" );
    
    public static final Property hasWikipediaArticle = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasWikipediaArticle" );
    
    public static final Property hasWikipediaMap = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasWikipediaMap" );
    
    public static final Property hasWikispeciesArticle = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasWikispeciesArticle" );
    
    public static final Property hasWildObsPage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hasWildObsPage" );
    
    /** <p>The URI to the Heterochresonym Name String</p> */
    public static final Property heterochresonymID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#heterochresonymID" );
    
    /** <p>The URI to the HeterotypicName Name String</p> */
    public static final Property heterotypicNameID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#heterotypicNameID" );
    
    /** <p>The URI to the HomotypicName Name String</p> */
    public static final Property homotypicNameID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#homotypicNameID" );
    
    public static final Property hybrid = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#hybrid" );
    
    public static final Property identificationDate = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identificationDate" );
    
    /** <p>The image of the identification label on a specimen</p> */
    public static final Property identificationHasLabelImage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identificationHasLabelImage" );
    
    /** <p>The link between an Identification and an Occurrence</p> */
    public static final Property identificationHasOcccurrence = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identificationHasOcccurrence" );
    
    /** <p>The link between an Identification and Species Concept, redundant with identifiedAs</p> */
    public static final Property identificationHasSpeciesConcept = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identificationHasSpeciesConcept" );
    
    /** <p>Method used to identify the individual, as a URI</p> */
    public static final Property identificationMethod = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identificationMethod" );
    
    public static final Property identificationNote = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identificationNote" );
    
    /** <p>Links an identification to an individual</p> */
    public static final Property identificationOfIndividual = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identificationOfIndividual" );
    
    /** <p>Links an identification to the URI for the reference used.</p> */
    public static final Property identificationReference = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identificationReference" );
    
    /** <p>Links an identification to the URI a human that made the identification as 
     *  URI</p>
     */
    public static final Property identifiedBy = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#identifiedBy" );
    
    public static final Property inClass = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inClass" );
    
    /** <p>Links a species concept to a Catalog of Life Class in an ontology</p> */
    public static final Property inCoLClass = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inCoLClass" );
    
    /** <p>Links a species concept to a Catalog of Life Family in an ontology</p> */
    public static final Property inCoLFamily = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inCoLFamily" );
    
    /** <p>Links a species concept to a Catalog of Life Kingdom in an ontology</p> */
    public static final Property inCoLKingdom = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inCoLKingdom" );
    
    /** <p>Links a species concept to a Catalog of Life Order in an ontology</p> */
    public static final Property inCoLOrder = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inCoLOrder" );
    
    /** <p>Links a species concept to a Catalog of Life Phylum in an ontology</p> */
    public static final Property inCoLPhylum = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inCoLPhylum" );
    
    /** <p>Links a species concept to a clade in the DBpedia ontology</p> */
    public static final Property inDBpediaClade = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inDBpediaClade" );
    
    public static final Property inFamily = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inFamily" );
    
    public static final Property inGenus = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inGenus" );
    
    public static final Property inInfraclass = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inInfraclass" );
    
    public static final Property inKingdom = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inKingdom" );
    
    public static final Property inOrder = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inOrder" );
    
    public static final Property inPhylum = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inPhylum" );
    
    public static final Property inSubclass = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inSubclass" );
    
    public static final Property inSubfamily = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inSubfamily" );
    
    public static final Property inSuborder = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inSuborder" );
    
    public static final Property inSuperfamily = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inSuperfamily" );
    
    public static final Property inSuperorder = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#inSuperorder" );
    
    /** <p>Links an individual to the most appropriate identification. Should be one.</p> */
    public static final Property individualHasCurrrentIdentificationAssertion = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#individualHasCurrrentIdentificationAssertion" );
    
    /** <p>Links an individual to an Area</p> */
    public static final Property individualHasObservedArea = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#individualHasObservedArea" );
    
    /** <p>Links an individual to an Occurrence, correct</p> */
    public static final Property individualHasOccurrence = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#individualHasOccurrence" );
    
    /** <p>Links an individual to the most appropriate identification. Zero to many</p> */
    public static final Property individualHasPreviousIdentificationAssertion = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#individualHasPreviousIdentificationAssertion" );
    
    /** <p>Links an individual a Species Concept</p> */
    public static final Property individualHasSpeciesConcept = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#individualHasSpeciesConcept" );
    
    /** <p>Links from an individual to a controlled vocabulary of URI's for the current 
     *  status of that individual</p>
     */
    public static final Property individualStatus = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#individualStatus" );
    
    /** <p>Intended to link an individual to a image. Should be subproperty of foaf:depiction</p> */
    public static final Property individualhasImage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#individualhasImage" );
    
    public static final Property infraspecificEpithet = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#infraspecificEpithet" );
    
    public static final Property institutionCode = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#institutionCode" );
    
    public static final Property isBioimagesPageOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#isBioimagesPageOf" );
    
    public static final Property isBugGuidePageOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#isBugGuidePageOf" );
    
    /** <p>The range is a page on the Encyclopedia of Life site.</p> */
    public static final Property isEOLPageOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#isEOLPageOf" );
    
    /** <p>This is to link between a taxon-like entity and a geographical area. The doman 
     *  and range are left blank so this can be used with different kinds of geographic 
     *  vocabularies and different kinds of taxon concept vocabularies. It should 
     *  not be used to indicate that a particular individual organism is expecten 
     *  in a geographical area, but to indicate that the species etc. is expected 
     *  in a particular geographical area. For instance, it would be used to indicate 
     *  that a species is expected in a particular state or province. The use should 
     *  approximate assertions similar to what one might find in a state or country 
     *  checklist.</p>
     */
    public static final Property isExpectedIn = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#isExpectedIn" );
    
    public static final Property isTaxonNameID_Of = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#isTaxonNameID_Of" );
    
    /** <p>Links a species concept to a Geonames URI where the relationship is unknown</p> */
    public static final Property isUnknownAboutIn = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#isUnknownAboutIn" );
    
    public static final Property isWikipediaArticleOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#isWikipediaArticleOf" );
    
    public static final Property isWikispeciesArticleOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#isWikispeciesArticleOf" );
    
    public static final Property kingdom = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#kingdom" );
    
    /** <p>The URI to the Last Author</p> */
    public static final Property lastAuthorID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#lastAuthorID" );
    
    public static final Property localityText = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#localityText" );
    
    public static final Property locationName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#locationName" );
    
    /** <p>The year that a name was published</p> */
    public static final Property nameYear = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#nameYear" );
    
    /** <p>Inverse of The year that a name was published</p> */
    public static final Property nameYearOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#nameYearOf" );
    
    /** <p>Links to the most appropriate NCBI Genus</p> */
    public static final Property ncbiGenus = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#ncbiGenus" );
    
    /** <p>Links to the most appropriate NCBI Species</p> */
    public static final Property ncbiSpecies = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#ncbiSpecies" );
    
    /** <p>Links an occurrence to an area</p> */
    public static final Property occurrenceHasArea = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#occurrenceHasArea" );
    
    /** <p>Links an occurrence to an individual</p> */
    public static final Property occurrenceHasIndividual = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#occurrenceHasIndividual" );
    
    /** <p>The image of the occurrence label on a specimen</p> */
    public static final Property occurrenceHasLabelImage = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#occurrenceHasLabelImage" );
    
    /** <p>Links an occurrence to a species concept</p> */
    public static final Property occurrenceHasSpeciesConcept = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#occurrenceHasSpeciesConcept" );
    
    /** <p>Links an Occurrence to Geonames Continent URI</p> */
    public static final Property occurrenceInContinent = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#occurrenceInContinent" );
    
    /** <p>Links an Occurrence to Geonames County URI</p> */
    public static final Property occurrenceInCounty = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#occurrenceInCounty" );
    
    public static final Property occurrenceInFeature = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#occurrenceInFeature" );
    
    /** <p>Links an Occurrence to Geonames StateProvince URI</p> */
    public static final Property occurrenceInStateProvince = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#occurrenceInStateProvince" );
    
    public static final Property order = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#order" );
    
    /** <p>The URI to the Original Name String</p> */
    public static final Property originalNameID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#originalNameID" );
    
    public static final Property originalNameID_Of = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#originalNameID_Of" );
    
    /** <p>The URI to the Orthochresonym Name String</p> */
    public static final Property orthochresonymID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#orthochresonymID" );
    
    public static final Property phylum = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#phylum" );
    
    /** <p>The year that document was pub</p> */
    public static final Property pubYearOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#pubYearOf" );
    
    /** <p>The radius in meters from a particular latitude, longitude point from within 
     *  which a thing was observed or collected.</p>
     */
    public static final Property radius = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#radius" );
    
    /** <p>The URI to the Orthochresonym Name String</p> */
    public static final Property relatedName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#relatedName" );
    
    /** <p>The URI to the Orthochresonym Name String</p> */
    public static final Property relatedNameOf = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#relatedNameOf" );
    
    /** <p>Links an Occurrence to a standard vocabulary of sampling protocols as URI's</p> */
    public static final Property samplingProtocol = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#samplingProtocol" );
    
    public static final Property scientificName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#scientificName" );
    
    /** <p>The author and year of the species description publication i.e (Baker, 1899)</p> */
    public static final Property scientificNameAuthorship = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#scientificNameAuthorship" );
    
    public static final Property scientificNameWithAuthor = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#scientificNameWithAuthor" );
    
    /** <p>Links an original description to a species type specimen</p> */
    public static final Property sodHasTypeSpecimen = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#sodHasTypeSpecimen" );
    
    /** <p>This describes the theoretical models behind the species concept. All species 
     *  concepts are at least based on an Objective Model. In addition the may also 
     *  be based on a Biological Species Model and or a Phylogenetic Species Model. 
     *  A species concept could be based on all three of these. This is to reflect 
     *  that there are several criteria used to support a species concept. It also 
     *  allows one to create a species concept for the domestic cat that is separate 
     *  from its wild relative. If one followed a strict phylogentic species model, 
     *  than the domestic cat would be considered to be a subclass of the species 
     *  Felis sylvestris. This would result in observations or references about the 
     *  domestic cat being interpreted as observations or references of the African 
     *  Wildcat Felis sylvestris.</p>
     */
    public static final Property speciesConceptBasedOn = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#speciesConceptBasedOn" );
    
    /** <p>Links a species to an area. Should be speciesConcept?</p> */
    public static final Property speciesConceptHasObservedArea = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#speciesConceptHasObservedArea" );
    
    /** <p>Links a species to an occurrence. Should be speciesConcept?</p> */
    public static final Property speciesConceptHasOcccurrence = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#speciesConceptHasOcccurrence" );
    
    /** <p>Links a species concept to a varitype specimen</p> */
    public static final Property speciesConcepthasVaritypeSpecimen = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#speciesConcepthasVaritypeSpecimen" );
    
    public static final Property specificEpithet = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#specificEpithet" );
    
    public static final Property startDate = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#startDate" );
    
    public static final Property stateProvince = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#stateProvince" );
    
    public static final Property surrogateName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#surrogateName" );
    
    public static final Property synonymName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#synonymName" );
    
    /** <p>The URI to the Taxon Name Group String</p> */
    public static final Property taxonNameGroupID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#taxonNameGroupID" );
    
    public static final Property taxonNameGroupID_Of = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#taxonNameGroupID_Of" );
    
    /** <p>The URI to the Taxon Name String</p> */
    public static final Property taxonNameID = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#taxonNameID" );
    
    /** <p>The URI to the Taxon Name String</p> */
    public static final Property taxonNameID_Of = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#taxonNameID_Of" );
    
    public static final Property taxonRank = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#taxonRank" );
    
    public static final Property thumbnail = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#thumbnail" );
    
    public static final Property trinomial = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#trinomial" );
    
    /** <p>Links specimen to an original species description</p> */
    public static final Property typeSpecimenHasSod = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#typeSpecimenHasSod" );
    
    /** <p>Links a varitype specimen to a species concept</p> */
    public static final Property varitypeSpecimenHasSpeciesConcept = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#varitypeSpecimenHasSpeciesConcept" );
    
    public static final Property yearBorn = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#yearBorn" );
    
    /** <p>The year that the species was originally described</p> */
    public static final Property yearDescribed = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#yearDescribed" );
    
    public static final Property yearDied = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#yearDied" );
    
    /** <p>The year that document was pub</p> */
    public static final Property yearPub = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#yearPub" );
    
    public static final Property zoologyAuthorName = m_model.createProperty( "http://lod.taxonconcept.org/ontology/txn.owl#zoologyAuthorName" );
    
    public static final Resource Area = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Area" );
    
    public static final Resource CommonNameID = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#CommonNameID" );
    
    public static final Resource FreshwaterHabitat = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#FreshwaterHabitat" );
    
    public static final Resource Gallery = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Gallery" );
    
    public static final Resource Habitat = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Habitat" );
    
    /** <p>An identification action. The identification of a specimen.</p> */
    public static final Resource Identification = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Identification" );
    
    public static final Resource Image = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Image" );
    
    public static final Resource MapImage = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#MapImage" );
    
    public static final Resource MarineHabitat = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#MarineHabitat" );
    
    public static final Resource Occurrence = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Occurrence" );
    
    public static final Resource OccurrenceSpecimenTag = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#OccurrenceSpecimenTag" );
    
    public static final Resource OccurrenceTaxonTag = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#OccurrenceTaxonTag" );
    
    public static final Resource OpenCycTaxon = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#OpenCycTaxon" );
    
    public static final Resource RankClass = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankClass" );
    
    public static final Resource RankDivision = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankDivision" );
    
    public static final Resource RankDomain = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankDomain" );
    
    public static final Resource RankFamily = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankFamily" );
    
    public static final Resource RankGenus = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankGenus" );
    
    public static final Resource RankInfraclass = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankInfraclass" );
    
    public static final Resource RankInfrakingdom = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankInfrakingdom" );
    
    public static final Resource RankInfraorder = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankInfraorder" );
    
    public static final Resource RankKingdom = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankKingdom" );
    
    public static final Resource RankOrder = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankOrder" );
    
    public static final Resource RankParvorder = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankParvorder" );
    
    public static final Resource RankPhylum = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankPhylum" );
    
    public static final Resource RankSpecies = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSpecies" );
    
    public static final Resource RankSubclass = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubclass" );
    
    public static final Resource RankSubdivision = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubdivision" );
    
    public static final Resource RankSubdomain = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubdomain" );
    
    public static final Resource RankSubfamily = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubfamily" );
    
    public static final Resource RankSubgenus = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubgenus" );
    
    public static final Resource RankSubkingdom = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubkingdom" );
    
    public static final Resource RankSuborder = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSuborder" );
    
    public static final Resource RankSubpecies = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubpecies" );
    
    public static final Resource RankSubphylum = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubphylum" );
    
    public static final Resource RankSubspecificAggregate = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSubspecificAggregate" );
    
    public static final Resource RankSuperclass = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSuperclass" );
    
    public static final Resource RankSuperdivision = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSuperdivision" );
    
    public static final Resource RankSuperfamily = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSuperfamily" );
    
    public static final Resource RankSuperkingdom = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSuperkingdom" );
    
    public static final Resource RankSuperorder = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSuperorder" );
    
    public static final Resource RankSuperphylum = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankSuperphylum" );
    
    public static final Resource RankTribe = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankTribe" );
    
    public static final Resource RankVariety = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#RankVariety" );
    
    /** <p>Someone who has authored a scientific article.</p> */
    public static final Resource ScientificAuthorPerson = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#ScientificAuthorPerson" );
    
    /** <p>Someone who has collected a scientific sample or specimen.</p> */
    public static final Resource ScientificCollectorPerson = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#ScientificCollectorPerson" );
    
    /** <p>Someone who has curated or entered data into a scientific data set.</p> */
    public static final Resource ScientificDataCuratorPerson = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#ScientificDataCuratorPerson" );
    
    /** <p>Someone who has identified a specimen.</p> */
    public static final Resource ScientificIdentifierPerson = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#ScientificIdentifierPerson" );
    
    public static final Resource ScientificNameID = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#ScientificNameID" );
    
    public static final Resource ScientificNameWithAuthorID = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#ScientificNameWithAuthorID" );
    
    /** <p>Class for Scientist a foaf:Person</p> */
    public static final Resource Scientist = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Scientist" );
    
    public static final Resource Sex = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Sex" );
    
    public static final Resource Sex_female = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Sex_female" );
    
    public static final Resource Sex_hermaphrodite = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Sex_hermaphrodite" );
    
    public static final Resource Sex_male = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Sex_male" );
    
    public static final Resource Sex_undetermined = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Sex_undetermined" );
    
    public static final Resource Sex_unknowable = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Sex_unknowable" );
    
    public static final Resource SpeciesConcept = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#SpeciesConcept" );
    
    /** <p>A tag like entity that can be used to indicate that an image is associated 
     *  with a specific species concept. Instances of SpeciesImageTag take the form 
     *  of the species concept URI with the fragment of #Image rather than #Species.</p>
     */
    public static final Resource SpeciesImageTag = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#SpeciesImageTag" );
    
    public static final Resource SpeciesIndividual = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#SpeciesIndividual" );
    
    /** <p>A tag like entity that can be used to indicate that an individual organism 
     *  is an associated with a particular species concept. Instances of SpeciesIndividualTag 
     *  take the form of the species concept URI with the fragment of #Individual 
     *  rather than #Species.</p>
     */
    public static final Resource SpeciesIndividualTag = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#SpeciesIndividualTag" );
    
    public static final Resource SpeciesModel = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#SpeciesModel" );
    
    public static final Resource SpeciesOriginalDescription = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#SpeciesOriginalDescription" );
    
    /** <p>A tag like entity for the NCBI Taxonomic Classification.</p> */
    public static final Resource SpeciesTaxonomyNCBI = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#SpeciesTaxonomyNCBI" );
    
    /** <p>A organismal specimen that is related to a specific organism, parts of an 
     *  individual organism, or a collection of these from several organisms. It should 
     *  be used for the smallest entity in a specimen database. Ideally there should 
     *  be at least one specimen per individual organism. Specimens consisting of 
     *  multiple individuals or multiple species often complicate analysis. If one 
     *  photo contains multiple entities, document these as separate specimens all 
     *  linked to the same photo.</p>
     */
    public static final Resource Specimen = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Specimen" );
    
    public static final Resource SurrogateNameID = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#SurrogateNameID" );
    
    /** <p>A particular taxonomic concept. Currently only species concepts are implemented, 
     *  however theoretically there could be additional subclasses of GenusConcepts, 
     *  FamilyConcepts etc. A SubspeciesConcept and lower are considered to be subclasses 
     *  of SpeciesConcepts, but one persons subspecies is often anothers species. 
     *  My current thinking is to represent individuals and observations of subspecies 
     *  as individuals and observations of the larger species concept. It has yet 
     *  to be implemented but I am considering recording these as observations and 
     *  individuals of a given species "in the form of" their subspecies indentifier 
     *  or name.</p>
     */
    public static final Resource TaxonConcept = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TaxonConcept" );
    
    public static final Resource TaxonNameGroupID = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TaxonNameGroupID" );
    
    public static final Resource TaxonNameID = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TaxonNameID" );
    
    public static final Resource TaxonOntology = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TaxonOntology" );
    
    public static final Resource TaxonRank = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TaxonRank" );
    
    /** <p>Class for a Taxonomist a subclass of dbpedia-owl:Scientist</p> */
    public static final Resource Taxonomist = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Taxonomist" );
    
    public static final Resource TerrestrialHabitat = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TerrestrialHabitat" );
    
    /** <p>Class for the Concept Year</p> */
    public static final Resource Year = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Year" );
    
    public static final Resource Status_Preliminary = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Status_Preliminary" );
    
    public static final Resource Status_Testing = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#Status_Testing" );
    
    public static final Resource TDWG2010_BioBlitz_Project = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TDWG2010_BioBlitz_Project" );
    
    public static final Resource TaxonConcept_Knowledge_Base_Project = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TaxonConcept_Knowledge_Base_Project" );
    
    public static final Resource TaxonConcept_Scheme = m_model.createResource( "http://lod.taxonconcept.org/ontology/txn.owl#TaxonConcept_Scheme" );
    
}
