package editor.ontologies; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://voag.linkedmodel.org/schema/voag# 
 * @author Auto-generated by schemagen on 14 Sep 2012 14:10 
 */
public class Voag {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://voag.linkedmodel.org/schema/voag#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property accountableEntityOf = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#accountableEntityOf" );
    
    public static final Property accountableFor = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#accountableFor" );
    
    public static final Property approves = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#approves" );
    
    public static final Property attributionText = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#attributionText" );
    
    public static final Property basedOn = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#basedOn" );
    
    public static final Property caption = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#caption" );
    
    public static final Property compatibleWith = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#compatibleWith" );
    
    public static final Property curatedGraphURI = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#curatedGraphURI" );
    
    public static final Property deprecated = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#deprecated" );
    
    /** <p>used to connect to the text describing disposition of something, for example, 
     *  a disposition of an issue</p>
     */
    public static final Property disposition = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#disposition" );
    
    public static final Property dispositionStatus = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#dispositionStatus" );
    
    public static final Property documentedAt = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#documentedAt" );
    
    public static final Property downloads = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#downloads" );
    
    public static final Property endDate = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#endDate" );
    
    public static final Property eventDate = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#eventDate" );
    
    public static final Property frequencyOfChange = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#frequencyOfChange" );
    
    public static final Property givesConcurrenceFor = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#givesConcurrenceFor" );
    
    public static final Property governs = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#governs" );
    
    public static final Property hasAccredidation = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasAccredidation" );
    
    public static final Property hasAnticipatedChangeType = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasAnticipatedChangeType" );
    
    public static final Property hasApplicableDocument = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasApplicableDocument" );
    
    public static final Property hasApprovalProcess = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasApprovalProcess" );
    
    public static final Property hasApprovalStatus = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasApprovalStatus" );
    
    public static final Property hasCatalogEntry = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasCatalogEntry" );
    
    public static final Property hasCategory = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasCategory" );
    
    public static final Property hasChangeManagementProcess = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasChangeManagementProcess" );
    
    public static final Property hasChangeType = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasChangeType" );
    
    public static final Property hasConfidentiality = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasConfidentiality" );
    
    public static final Property hasGovernance = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasGovernance" );
    
    public static final Property hasGovernanceEvent = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasGovernanceEvent" );
    
    public static final Property hasIdentifier = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasIdentifier" );
    
    public static final Property hasIssue = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasIssue" );
    
    public static final Property hasIssueResolutionProcess = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasIssueResolutionProcess" );
    
    public static final Property hasLicenseType = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasLicenseType" );
    
    public static final Property hasLogo = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasLogo" );
    
    public static final Property hasMaturity = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasMaturity" );
    
    public static final Property hasNormativeDocument = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasNormativeDocument" );
    
    public static final Property hasOntologyArchitectureDiagram = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasOntologyArchitectureDiagram" );
    
    public static final Property hasOwner = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasOwner" );
    
    public static final Property hasPedigree = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasPedigree" );
    
    public static final Property hasProcess = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasProcess" );
    
    public static final Property hasProtocol = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasProtocol" );
    
    public static final Property hasProvenance = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasProvenance" );
    
    public static final Property hasReferenceDocument = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasReferenceDocument" );
    
    public static final Property hasStakeholder = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasStakeholder" );
    
    public static final Property hasStatus = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasStatus" );
    
    public static final Property hasSteward = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasSteward" );
    
    public static final Property hasValue = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#hasValue" );
    
    public static final Property height = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#height" );
    
    public static final Property id = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#id" );
    
    public static final Property image = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#image" );
    
    public static final Property imageMap = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#imageMap" );
    
    public static final Property incompatibleWith = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#incompatibleWith" );
    
    public static final Property instigatedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#instigatedBy" );
    
    public static final Property instigatingEvent = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#instigatingEvent" );
    
    public static final Property intent = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#intent" );
    
    public static final Property interestIn = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#interestIn" );
    
    public static final Property isApprovedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#isApprovedBy" );
    
    public static final Property isFOSS = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#isFOSS" );
    
    public static final Property isGovernedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#isGovernedBy" );
    
    public static final Property isITAR = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#isITAR" );
    
    public static final Property isInterestOf = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#isInterestOf" );
    
    public static final Property jurisdiction = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#jurisdiction" );
    
    public static final Property legalcode = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#legalcode" );
    
    public static final Property licence = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#licence" );
    
    public static final Property longDescription = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#longDescription" );
    
    public static final Property mayNeedConcurrenceFrom = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#mayNeedConcurrenceFrom" );
    
    public static final Property morePermissions = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#morePermissions" );
    
    public static final Property normativeReference = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#normativeReference" );
    
    public static final Property obsoletedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#obsoletedBy" );
    
    public static final Property ownedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#ownedBy" );
    
    public static final Property owner = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#owner" );
    
    public static final Property owns = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#owns" );
    
    public static final Property participant = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#participant" );
    
    public static final Property performedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#performedBy" );
    
    public static final Property permits = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#permits" );
    
    public static final Property pointOfContact = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#pointOfContact" );
    
    public static final Property preparedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#preparedBy" );
    
    public static final Property priority = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#priority" );
    
    public static final Property prohibits = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#prohibits" );
    
    public static final Property proprietary = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#proprietary" );
    
    /** <p>This property connects two issue events. Issues connected by this property 
     *  must be about the same subject</p>
     */
    public static final Property relatedIssue = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#relatedIssue" );
    
    public static final Property relatedTo = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#relatedTo" );
    
    public static final Property releaseDate = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#releaseDate" );
    
    public static final Property requires = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#requires" );
    
    public static final Property reviewedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#reviewedBy" );
    
    public static final Property reviews = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#reviews" );
    
    public static final Property revision = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#revision" );
    
    public static final Property revisionNumber = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#revisionNumber" );
    
    public static final Property rights = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#rights" );
    
    public static final Property shortDescription = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#shortDescription" );
    
    public static final Property source = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#source" );
    
    public static final Property startDate = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#startDate" );
    
    public static final Property subject = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#subject" );
    
    public static final Property submittedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#submittedBy" );
    
    public static final Property supercededBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#supercededBy" );
    
    public static final Property supercedes = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#supercedes" );
    
    public static final Property supervisedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#supervisedBy" );
    
    public static final Property timestamp = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#timestamp" );
    
    public static final Property title = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#title" );
    
    public static final Property url = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#url" );
    
    public static final Property urlForHTML = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#urlForHTML" );
    
    public static final Property urlOfRDFfile = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#urlOfRDFfile" );
    
    public static final Property urlOfTurtleFile = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#urlOfTurtleFile" );
    
    public static final Property usage = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#usage" );
    
    public static final Property useGuidelines = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#useGuidelines" );
    
    public static final Property usedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#usedBy" );
    
    public static final Property userID = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#userID" );
    
    public static final Property width = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#width" );
    
    public static final Property withAttributionTo = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#withAttributionTo" );
    
    public static final Property witnessTo = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#witnessTo" );
    
    public static final Property witnessedBy = m_model.createProperty( "http://voag.linkedmodel.org/schema/voag#witnessedBy" );
    
    public static final Resource Accredidation = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Accredidation" );
    
    public static final Resource AdministrativeEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#AdministrativeEvent" );
    
    public static final Resource ApprovalEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ApprovalEvent" );
    
    public static final Resource ApprovalProcess = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ApprovalProcess" );
    
    public static final Resource Attribution = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Attribution" );
    
    public static final Resource AttributionLogo = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#AttributionLogo" );
    
    public static final Resource Catalog = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Catalog" );
    
    public static final Resource ChangeFrequency = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ChangeFrequency" );
    
    public static final Resource ChangeManagementProcess = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ChangeManagementProcess" );
    
    public static final Resource ChangeType = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ChangeType" );
    
    public static final Resource ConcurrenceEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ConcurrenceEvent" );
    
    public static final Resource ConfidentialityLevel = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ConfidentialityLevel" );
    
    public static final Resource CreativeCommonsJurisdiction = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CreativeCommonsJurisdiction" );
    
    public static final Resource CreativeCommonsPermission = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CreativeCommonsPermission" );
    
    public static final Resource CreativeCommonsProhibition = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CreativeCommonsProhibition" );
    
    public static final Resource CreativeCommonsRequirement = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CreativeCommonsRequirement" );
    
    public static final Resource CreativeCommonsWork = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CreativeCommonsWork" );
    
    public static final Resource DeletionEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#DeletionEvent" );
    
    public static final Resource DesignatedGovernanceRole = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#DesignatedGovernanceRole" );
    
    public static final Resource Document = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Document" );
    
    public static final Resource EnumeratedValue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#EnumeratedValue" );
    
    public static final Resource Event = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Event" );
    
    public static final Resource Figure = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Figure" );
    
    public static final Resource Governance = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Governance" );
    
    public static final Resource GovernanceEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GovernanceEvent" );
    
    public static final Resource GovernanceProcess = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GovernanceProcess" );
    
    public static final Resource GovernanceProtocol = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GovernanceProtocol" );
    
    public static final Resource GovernanceRole = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GovernanceRole" );
    
    public static final Resource GovernedObject = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GovernedObject" );
    
    public static final Resource GovernedService = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GovernedService" );
    
    public static final Resource Graph = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Graph" );
    
    public static final Resource Icon = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Icon" );
    
    public static final Resource Image = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Image" );
    
    public static final Resource Issue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Issue" );
    
    public static final Resource IssueResolutionProcess = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#IssueResolutionProcess" );
    
    public static final Resource IssueStatus = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#IssueStatus" );
    
    public static final Resource LicenseModel = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#LicenseModel" );
    
    public static final Resource LinkedModelCatalog = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#LinkedModelCatalog" );
    
    public static final Resource Logo = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Logo" );
    
    public static final Resource Maturity = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Maturity" );
    
    public static final Resource NonConcurrenceEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NonConcurrenceEvent" );
    
    public static final Resource Organization = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Organization" );
    
    public static final Resource OrganizationLogo = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OrganizationLogo" );
    
    public static final Resource Party = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Party" );
    
    public static final Resource Pedigree = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Pedigree" );
    
    public static final Resource Person = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Person" );
    
    public static final Resource PriorityValue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PriorityValue" );
    
    public static final Resource Process = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Process" );
    
    public static final Resource ProductLogo = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ProductLogo" );
    
    public static final Resource Provenance = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Provenance" );
    
    public static final Resource PublicationStatus = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PublicationStatus" );
    
    public static final Resource Qualifier = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Qualifier" );
    
    public static final Resource RejectionEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#RejectionEvent" );
    
    public static final Resource RetreivalEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#RetreivalEvent" );
    
    public static final Resource ReviewEvent = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ReviewEvent" );
    
    public static final Resource SchemaGraph = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SchemaGraph" );
    
    public static final Resource Service = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Service" );
    
    public static final Resource StakeholderGroup = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#StakeholderGroup" );
    
    public static final Resource Standard = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Standard" );
    
    public static final Resource VocabGraph = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#VocabGraph" );
    
    public static final Resource ACADEMIIC_FREE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ACADEMIIC_FREE_LICENSE" );
    
    public static final Resource ACDL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ACDL_V1PT0" );
    
    public static final Resource AGPL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#AGPL_V1PT0" );
    
    public static final Resource AGPL_V3PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#AGPL_V3PT0" );
    
    public static final Resource APACHE_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#APACHE_V1PT0" );
    
    public static final Resource APACHE_V1PT1 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#APACHE_V1PT1" );
    
    public static final Resource APACHE_V2PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#APACHE_V2PT0" );
    
    public static final Resource APSL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#APSL_V1PT0" );
    
    public static final Resource APSL_V1PTX = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#APSL_V1PTX" );
    
    public static final Resource APSL_V2 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#APSL_V2" );
    
    public static final Resource ARPHIC_PUBLIC_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ARPHIC_PUBLIC_LICENSE" );
    
    public static final Resource ARTISTIC_LICENSE_2PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ARTISTIC_LICENSE_2PT0" );
    
    public static final Resource Annually = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Annually" );
    
    public static final Resource AppendChange = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#AppendChange" );
    
    public static final Resource ApprovedIssue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ApprovedIssue" );
    
    public static final Resource BERKELEY_DATABASE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#BERKELEY_DATABASE_LICENSE" );
    
    public static final Resource BITTORRENT_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#BITTORRENT_LICENSE" );
    
    public static final Resource BOOST_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#BOOST_LICENSE" );
    
    public static final Resource BSD_ORIGINAL_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#BSD_ORIGINAL_LICENSE" );
    
    public static final Resource BiMonthly = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#BiMonthly" );
    
    public static final Resource BiQuarterly = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#BiQuarterly" );
    
    public static final Resource BiWeekly = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#BiWeekly" );
    
    public static final Resource CC_SHAREALIKE_3PT0_US = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CC-SHAREALIKE_3PT0-US" );
    
    public static final Resource CC0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CC0" );
    
    public static final Resource CCBY_ND = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCBY-ND" );
    
    public static final Resource CCBY_SA = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCBY-SA" );
    
    public static final Resource CCBY_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCBY_LICENSE" );
    
    public static final Resource CCPH_CommercialUse = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCPH_CommercialUse" );
    
    public static final Resource CCPH_HighIncomeNationUse = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCPH_HighIncomeNationUse" );
    
    public static final Resource CCP_DerivativeWorks = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCP_DerivativeWorks" );
    
    public static final Resource CCP_Distribution = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCP_Distribution" );
    
    public static final Resource CCP_Reproduction = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCP_Reproduction" );
    
    public static final Resource CCP_Sharing = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCP_Sharing" );
    
    public static final Resource CCR_Attribution = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCR_Attribution" );
    
    public static final Resource CCR_Copyleft = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCR_Copyleft" );
    
    public static final Resource CCR_LesserCopyleft = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCR_LesserCopyleft" );
    
    public static final Resource CCR_Notice = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCR_Notice" );
    
    public static final Resource CCR_ShareAlike = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCR_ShareAlike" );
    
    public static final Resource CCR_SourceCode = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CCR_SourceCode" );
    
    public static final Resource CDDL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CDDL_V1PT0" );
    
    public static final Resource CECILL_V2 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CECILL_V2" );
    
    public static final Resource CLEAR_BSD = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CLEAR_BSD" );
    
    public static final Resource CL_None = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CL_None" );
    
    public static final Resource CL_Restricted = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CL_Restricted" );
    
    public static final Resource CL_Secret = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CL_Secret" );
    
    public static final Resource CL_SensitiveButUnclassified = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CL_SensitiveButUnclassified" );
    
    public static final Resource CL_TopSecret = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CL_TopSecret" );
    
    public static final Resource CL_Unclassified = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CL_Unclassified" );
    
    public static final Resource COMMON_PUBLIC_LICENSE_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#COMMON_PUBLIC_LICENSE_V1PT0" );
    
    public static final Resource CONDOR_PUBLIC_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CONDOR_PUBLIC_LICENSE" );
    
    public static final Resource CPAL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CPAL" );
    
    public static final Resource CRYPTIX_GENERAL_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#CRYPTIX_GENERAL_LICENSE" );
    
    public static final Resource ClosedIssue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ClosedIssue" );
    
    public static final Resource DSL_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#DSL_LICENSE" );
    
    public static final Resource Daily = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Daily" );
    
    public static final Resource DeferredIssue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#DeferredIssue" );
    
    public static final Resource DisapprovedIssue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#DisapprovedIssue" );
    
    public static final Resource DocumentationChange = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#DocumentationChange" );
    
    public static final Resource ECL_V2PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ECL_V2PT0" );
    
    public static final Resource ECOS_V2PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ECOS_V2PT0" );
    
    public static final Resource ECPAT_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ECPAT_LICENSE" );
    
    public static final Resource EIFFEL_FORUM_LICENSE_V2 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#EIFFEL_FORUM_LICENSE_V2" );
    
    public static final Resource EPL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#EPL_V1PT0" );
    
    public static final Resource EUPL_V1PT1 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#EUPL_V1PT1" );
    
    public static final Resource EU_DATAGRID_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#EU_DATAGRID_LICENSE" );
    
    public static final Resource EarlyAdoption = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#EarlyAdoption" );
    
    public static final Resource Experimental = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Experimental" );
    
    public static final Resource FREEBSD_DL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#FREEBSD_DL" );
    
    public static final Resource FREETYPE_PROJECT_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#FREETYPE_PROJECT_LICENSE" );
    
    public static final Resource FREE_ART_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#FREE_ART_LICENSE" );
    
    public static final Resource FREE_BSD_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#FREE_BSD_LICENSE" );
    
    public static final Resource GNU_FDL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GNU-FDL" );
    
    public static final Resource GNU_GPL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GNU-GPL" );
    
    public static final Resource GNU_GPL_V2 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GNU-GPL_V2" );
    
    public static final Resource GNU_GPL_V3 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GNU-GPL_V3" );
    
    public static final Resource GNU_LGPL_V2PT1 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GNU-LGPL_V2PT1" );
    
    public static final Resource GNU_LGPL_V3 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GNU-LGPL_V3" );
    
    public static final Resource GNU_ALL_PERMISSIVE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GNU_ALL_PERMISSIVE_LICENSE" );
    
    public static final Resource GNU_VERBATIM_COPYING_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GNU_VERBATIM_COPYING_LICENSE" );
    
    public static final Resource GPLPA = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GPLPA" );
    
    public static final Resource GR_Authorizer = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GR_Authorizer" );
    
    public static final Resource GR_Steward = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GR_Steward" );
    
    public static final Resource GR_Submitter = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#GR_Submitter" );
    
    public static final Resource HESSLA = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#HESSLA" );
    
    public static final Resource IBM_PUBLIC_LICENSE_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#IBM_PUBLIC_LICENSE_V1PT0" );
    
    public static final Resource IJG_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#IJG_LICENSE" );
    
    public static final Resource IMATRIX_STANDARD_FUNCTION_LIBRARY_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#IMATRIX_STANDARD_FUNCTION_LIBRARY_LICENSE" );
    
    public static final Resource IMLIB2_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#IMLIB2_LICENSE" );
    
    public static final Resource INTEL_OPEN_SOURCE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#INTEL_OPEN_SOURCE_LICENSE" );
    
    public static final Resource IPL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#IPL_V1PT0" );
    
    public static final Resource ISC_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ISC_LICENSE" );
    
    public static final Resource InDevelopment = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#InDevelopment" );
    
    public static final Resource JAHIA_COMMUNITY_SOURCE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#JAHIA_COMMUNITY_SOURCE_LICENSE" );
    
    public static final Resource JOSL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#JOSL_V1PT0" );
    
    public static final Resource JSON_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#JSON_LICENSE" );
    
    public static final Resource LPPL_V1PT2 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#LPPL_V1PT2" );
    
    public static final Resource LPPL_V1PT3A = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#LPPL_V1PT3A" );
    
    public static final Resource LUCENT_PUBLIC_LICENSE_V1PT02 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#LUCENT_PUBLIC_LICENSE_V1PT02" );
    
    public static final Resource LinkedModelLogo_200x80 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#LinkedModelLogo-200x80" );
    
    public static final Resource MODIFIED_BSD_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#MODIFIED_BSD_LICENSE" );
    
    public static final Resource MPL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#MPL" );
    
    public static final Resource MS_LPL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#MS-LPL" );
    
    public static final Resource MS_LRL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#MS-LRL" );
    
    public static final Resource MS_PL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#MS-PL" );
    
    public static final Resource MS_RL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#MS-RL" );
    
    public static final Resource MS_RRL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#MS-RRL" );
    
    public static final Resource MS_SSL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#MS-SSL" );
    
    public static final Resource ModificationChange = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ModificationChange" );
    
    public static final Resource Monthly = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Monthly" );
    
    public static final Resource NASA_OPEN_SOURCE_AGREEMENT = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NASA_OPEN_SOURCE_AGREEMENT" );
    
    public static final Resource NCSA_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NCSA_LICENSE" );
    
    public static final Resource NOKIA_OPEN_SOURCE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NOKIA_OPEN_SOURCE_LICENSE" );
    
    public static final Resource NOSL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NOSL_V1PT0" );
    
    public static final Resource NPL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NPL" );
    
    public static final Resource Never = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Never" );
    
    public static final Resource NoAttributionSpecified = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NoAttributionSpecified" );
    
    public static final Resource NoGovernanceSpecified = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NoGovernanceSpecified" );
    
    public static final Resource NoPedigreeSpecified = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NoPedigreeSpecified" );
    
    public static final Resource NoProvenanceSpecified = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NoProvenanceSpecified" );
    
    public static final Resource NonIssue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#NonIssue" );
    
    public static final Resource OCL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OCL" );
    
    public static final Resource OPENLDAP_LICENSE_V2PT7 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OPENLDAP_LICENSE_V2PT7" );
    
    public static final Resource OPEN_DIRECTORY_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OPEN_DIRECTORY_LICENSE" );
    
    public static final Resource OPEN_PUBLICATION_LICENSE_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OPEN_PUBLICATION_LICENSE_V1PT0" );
    
    public static final Resource OPEN_SOFTWARE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OPEN_SOFTWARE_LICENSE" );
    
    public static final Resource OPEN_SSL_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OPEN_SSL_LICENSE" );
    
    public static final Resource OPL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OPL" );
    
    public static final Resource OpenIssue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#OpenIssue" );
    
    public static final Resource PHORUM_LICENSE_V2PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PHORUM_LICENSE_V2PT0" );
    
    public static final Resource PHP_LICENSE_V3PT01 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PHP_LICENSE_V3PT01" );
    
    public static final Resource PS_Draft = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PS_Draft" );
    
    public static final Resource PS_Final = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PS_Final" );
    
    public static final Resource PS_Interim = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PS_Interim" );
    
    public static final Resource PS_Obsolete = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PS_Obsolete" );
    
    public static final Resource PS_Review = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PS_Review" );
    
    public static final Resource PS_Unknown = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PS_Unknown" );
    
    public static final Resource PV_HighPriority = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PV_HighPriority" );
    
    public static final Resource PV_LowPriority = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PV_LowPriority" );
    
    public static final Resource PV_MediumPriority = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PV_MediumPriority" );
    
    public static final Resource PV_NotApplicable = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PV_NotApplicable" );
    
    public static final Resource PV_ToBeDetermined = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PV_ToBeDetermined" );
    
    public static final Resource PYTHON_LICENSE_V1PT6B1_THROUGH_2PT0_AND_2PT1 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PYTHON_LICENSE_V1PT6B1_THROUGH_2PT0_AND_2PT1" );
    
    public static final Resource PYTHON_LICENSE_V2PT0PT1_AND_OTHERS = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#PYTHON_LICENSE_V2PT0PT1_AND_OTHERS" );
    
    public static final Resource Proposed = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Proposed" );
    
    public static final Resource QPL_LICENSE_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#QPL_LICENSE_V1PT0" );
    
    public static final Resource Quarterly = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Quarterly" );
    
    public static final Resource RDFIcon_32X35 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#RDFIcon-32X35" );
    
    public static final Resource RPL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#RPL" );
    
    public static final Resource RPSL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#RPSL_V1PT0" );
    
    public static final Resource RUBY_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#RUBY_LICENSE" );
    
    public static final Resource RefactoringChange = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#RefactoringChange" );
    
    public static final Resource ResolvedIssue = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ResolvedIssue" );
    
    public static final Resource SGI_FREE_SOFTWARE_LICENSE_B_V2PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SGI_FREE_SOFTWARE_LICENSE_B_V2PT0" );
    
    public static final Resource SIL_OFL_V1PT1 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SIL-OFL_V1PT1" );
    
    public static final Resource SISSL_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SISSL_V1PT0" );
    
    public static final Resource SML = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SML" );
    
    public static final Resource SPARQLIcon_80X15 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SPARQLIcon-80X15" );
    
    public static final Resource SPL = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SPL" );
    
    public static final Resource STANDARD_ML_OF_NJ_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#STANDARD_ML_OF_NJ_LICENSE" );
    
    public static final Resource SYSTEMC_V3PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SYSTEMC_V3PT0" );
    
    public static final Resource SomeAdoption = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#SomeAdoption" );
    
    public static final Resource TopQuadrantAttribution = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#TopQuadrantAttribution" );
    
    public static final Resource TopQuadrantLogo_613x150 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#TopQuadrantLogo-613x150" );
    
    public static final Resource TurtleIcon_32bX35 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#TurtleIcon-32bX35" );
    
    public static final Resource UNICODE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#UNICODE_LICENSE" );
    
    public static final Resource UNLICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#UNLICENSE" );
    
    public static final Resource UncertainFrequency = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#UncertainFrequency" );
    
    public static final Resource UnknownMaturity = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#UnknownMaturity" );
    
    public static final Resource UtahPublicLicense = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#UtahPublicLicense" );
    
    public static final Resource VIM_LICENSE_V6PT1_OR_LATER = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#VIM_LICENSE_V6PT1_OR_LATER" );
    
    public static final Resource VOAG_OntologyLogo_360x110 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#VOAG-OntologyLogo_360x110" );
    
    public static final Resource W3C_SOFTWARE_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#W3C_SOFTWARE_LICENSE" );
    
    public static final Resource WEBM_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#WEBM_LICENSE" );
    
    public static final Resource WTFPL_V2 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#WTFPL_V2" );
    
    public static final Resource Weekly = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#Weekly" );
    
    public static final Resource WidelyAdopted = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#WidelyAdopted" );
    
    public static final Resource X11_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#X11_LICENSE" );
    
    public static final Resource XFREE86_LICENSE_V1PT1 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#XFREE86_LICENSE_V1PT1" );
    
    public static final Resource XINETD_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#XINETD_LICENSE" );
    
    public static final Resource YAHOO_PUBLIC_LICENSE_V1PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#YAHOO_PUBLIC_LICENSE_V1PT0" );
    
    public static final Resource ZEND_LICENSE_V2PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ZEND_LICENSE_V2PT0" );
    
    public static final Resource ZLIB_LICENSE = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ZLIB_LICENSE" );
    
    public static final Resource ZOPE_PUBLICE_LICENSE_V1 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ZOPE_PUBLICE_LICENSE_V1" );
    
    public static final Resource ZOPE_PUBLIC_LICENSE_V2PT0 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ZOPE_PUBLIC_LICENSE_V2PT0" );
    
    public static final Resource ZOPE_PUBLIC_LICENSE_V2PT1 = m_model.createResource( "http://voag.linkedmodel.org/schema/voag#ZOPE_PUBLIC_LICENSE_V2PT1" );
    
}
